[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "U-SDMX"
version = "0.0.1"
authors = [
  { name="Daniele Olivotti"},
]
description = "A SDMX reader package"
readme = "README.md"
requires-python = ">=3.7"